# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20170106_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, to='questions.Tag'),
        ),
    ]
