# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20170205_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_in_dota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
