# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20170205_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='questions/media/profile_photos'),
        ),
    ]
