# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20170207_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
