# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20170209_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/question.jpg', upload_to='profile_photos'),
        ),
    ]
