# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20170215_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_url',
        ),
    ]
